---
- hosts: all
  vars_files:
    - vars/secret.yml
  tasks:
    - name: Create User {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"
        state: present
      register: result

    - ansible.builtin.debug:
        var: result
