---
- hosts: all_worker
  become: true
  tasks:
    - name: Create /var/log/ansible.log
      file:
        path: /var/log/ansible.log
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Add initial log entry
      lineinfile:
        path: /var/log/ansible.log
        line: "Ansible playbook run started on {{ ansible_date_time.iso8601 }}"
        create: true
