---
- hosts: all
  tasks:
    - name: Install systemd-timesyncd
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure systemd-timesyncd is installed
      ansible.builtin.apt:
        name: systemd-timesyncd
        state: present

    - name: Ensure systemd-timesyncd is enabled and started
      ansible.builtin.systemd:
        name: systemd-timesyncd
        enabled: true
        state: started

    - name: set ntp sync to true
      ansible.builtin.command:
        cmd: timedatectl set-ntp true

    - name: set timezone to Asia/Seoul
      ansible.builtin.timezone:
        name: Asia/Seoul

    - name: Verify time sync status
      ansible.builtin.command:
        cmd: timedatectl
      register: timedatectl_output

    - name: Print timedatectl
      ansible.builtin.debug:
        msg: "{{ timedatectl_output.stdout }}"

    - name: apt update
      ansible.builtin.command:
        cmd: apt update
