---
# config_repo.yml
- hosts: repo_node
  vars:
    repo_url: http://192.168.100.7/repo

  roles:
    - role: httpd

  post_tasks:
    - name: Check http service
      ansible.builtin.uri:
        url: "{{ repo.url }}"
        return_content: true
      register: check_result
      failed_when: check_result.status != 200

    - name: Print result
      ansible.builtin.debug:
        var: check_result.status
