---
# set_nfs_storage.yml
- hosts: nfs_server
  vars_files: ./vars_share_path.yml
  roles:
    - role: nfs_server

- hosts: nfs_client
  vars_files: ./vars_share_path.yml
  roles:
    - role: nfs_client
