---
- hosts: masters
  vars_files: vars_pw_rule.yml
  tasks:
    - name: Install libpam-pwquality
      ansible.builtin.apt:
        name: libpam-pwquality
        state: present
      when: ansible_facts.os_family == "Debian"
    - name: Check if pwquality.conf exists
      ansible.builtin.stat:
        path: /etc/security/pwquality
      register: pwquality_conf_stat

        
    - name: Backup pwquality.conf
      ansible.builtin.copy:
        src: /etc/security/pwquality.conf
        dest: /etc/security/pwquality.conf.bak
      when: pwquality_conf_stat.stat.exists

    - name: Copy pwquality.conf.j2 at /etc/security
      ansible.builtin.template:
        src: pwquality.conf.j2
        dest: /etc/security/pwquality.conf
        mode: '0644'
