---
# set_ip.yml
- hosts: masters
  vars:
    fedora_os:
      - CentOS
      - RedHat
    net_info:
      - con_name: enp0s1
        ip_addr: 192.168.0.14/24
        ip_gw: 192.168.0.1
        ip_dns: 192.168.0.1

  tasks:
    - name: Include role in CentOS and RedHat
      ansible.builtin.include_role:
        name: nmcli
      when: ansible_facts.distribution in fedora_os

    - name: Include role in Ubuntu
      ansible.builtin.include_role:
        name: netplan
      when: ansible_facts.distribution == "Ubuntu"
