---
- hosts: master
  pre_tasks:
    - name: Print Start role
      ansible.builtin.debug:
        msg: "Let's start role play"

  roles:
    - role: simple-role
    - role: simple-role2

  tasks:
    - name: Curl test
      ansible.builtin.uri:
        url: http://{{ ansible_facts.default_ipv4.address }}
        return_content: true
      register: curl_result
      notify: Print result
      changed_when: true

  post_tasks:
    - name: Print Finish role
      ansible.builtin.debug:
        msg: "Finish role play"

  handlers:
    - name: Print result
      ansible.builtin.debug:
        msg: "{{ curl_result.content }}"
