---
---
# roles/httpd/tasks/main.yml
- name: Make repo dir
  ansible.builtin.file:
    path: "{{ repo.dir }}"
    state: directory

- name: Install httpd
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ httpd_servie }}"

- name: Copy repo.conf file
  ansible.builtin.copy:
    src: ../files/repo.conf
    dest: /etc/httpd/conf.d/
  notify:
    - Restart httpd
    - Reconfigure sefcontext

- name: Add http to firewalld
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: Reload firewalld
